### ISSUE TITLE
Feature Request: Store selected_unit along with base_units to determine appropriate value for display

### ISSUE THREAD

**Issue by apaxson** [CarliJoy/django-pint#89] opened 2023-08-21 17:45 UTC
On first edit of a form page, you can select the unit to enter.  Django-Pint will then convert it to the base_units to be stored.
The challenge with that is, the next time you edit the value, it defaults back to the base unit.

For example:

Edit1 for field with "minutes" as base_unit, entered:

8 days

After Save 1, the model stores 11520 (in minutes)

Edit2 for field:

value shows 11520 in minutes.  The user says "no, that should be 'days'" and selects that.  Doesn't realize the data doesn't auto update, and now you store 11520 days into the DB.

Or, the value shows 11520 minutes, but the end-user doesn't know that's 8 days.

**Comment by CarliJoy** [comment] 2023-08-22 11:06
Duplicate of #38

**Closed by CarliJoy** 2023-08-22 11:06 UTC
